"""Split rule path

Revision ID: 088e552dd96b
Revises: 7b2a4755c34b
Create Date: 2025-08-19 14:53:44.913922

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '088e552dd96b'
down_revision: Union[str, Sequence[str], None] = '7b2a4755c34b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rules', sa.Column('schema', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('rules', sa.Column('table_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('rules', sa.Column('column_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('rules', 'path')
    op.drop_constraint(op.f('uq_rules_users_name'), 'users', type_='unique')
    op.create_unique_constraint('uq_users_username', 'users', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_catalog_name', 'users', type_='unique')
    op.create_unique_constraint(op.f('uq_rules_users_name'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.add_column('rules', sa.Column('path', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('rules', 'column_name')
    op.drop_column('rules', 'table_name')
    op.drop_column('rules', 'schema')
    # ### end Alembic commands ###
