"""Add user and password to catalog

Revision ID: 44104adecd3f
Revises: 0c58a38876bf
Create Date: 2025-08-17 19:02:31.967010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '44104adecd3f'
down_revision: Union[str, Sequence[str], None] = '0c58a38876bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('catalogs', sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('catalogs', sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.alter_column('catalogs', 'url',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('catalogs', 'url',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.drop_column('catalogs', 'password')
    op.drop_column('catalogs', 'user')
    # ### end Alembic commands ###
