"""Add rules model

Revision ID: 7b2a4755c34b
Revises: 48264c38fbbb
Create Date: 2025-08-18 23:42:05.896573

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '7b2a4755c34b'
down_revision: Union[str, Sequence[str], None] = '48264c38fbbb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('path', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('allow', sa.Boolean(), nullable=False),
    sa.Column('effect', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('catalog_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['catalog_id'], ['catalogs.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rules_catalog_id'), 'rules', ['catalog_id'], unique=False)
    op.create_index(op.f('ix_rules_user_id'), 'rules', ['user_id'], unique=False)
    op.drop_constraint(op.f('uq_user_username'), 'users', type_='unique')
    op.create_unique_constraint('uq_rules_users_name', 'users', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_catalog_name', 'users', type_='unique')
    op.create_unique_constraint(op.f('uq_user_username'), 'users', ['username'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_rules_user_id'), table_name='rules')
    op.drop_index(op.f('ix_rules_catalog_id'), table_name='rules')
    op.drop_table('rules')
    # ### end Alembic commands ###
