"""add check constraint on catalogs.name

Revision ID: d51ba73b550a
Revises: 088e552dd96b
Create Date: 2025-09-12 13:03:59.086502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd51ba73b550a'
down_revision: Union[str, Sequence[str], None] = '088e552dd96b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("catalogs", "name", existing_type=sa.String(), nullable=False)
    op.create_check_constraint(
        "ck_catalog_name_lower_az",
        "catalogs",
        "name ~ '^[a-z]+$'"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("ck_catalog_name_lower_az", "catalogs", type_="check")
    # ### end Alembic commands ###
