stages:
  - test
  - release
  - build

# Vars
variables:
  COMPOSE_PROJECT_NAME: "maskql-${CI_PIPELINE_ID}"

tests:
  stage: test
  tags:
    - unix
    - test
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
    GIT_SUBMODULE_FORCE_HTTPS: "true"

  before_script:
    - export HOST_UID="$(id -u)"
    - export HOST_GID="$(id -g)"
    
  script:
    - cp ./.env.example ./.env
    - uv run tox
  artifacts:
    when: always
    expire_in: 7 days
    paths:
      - .tox/**/log/**

release:
  stage: release
  tags:
    - unix
  needs: ["tests"]
  only: 
    - main
  variables:
    GIT_STRATEGY: fetch
    GIT_DEPTH: "0"
  before_script:
    - set -e 
    - git config user.name  "MaskQL CI"
    - git config user.email "ci@maskql.local"
    # Token & certificat
    - export GITLAB_TOKEN="$push_token"
    - export REQUESTS_CA_BUNDLE="$GITLAB_CA"
    - export SSL_CERT_FILE="$GITLAB_CA"
    - export GIT_SSL_CAINFO="$GITLAB_CA"
    - git fetch --tags --force
    - git checkout -B "$CI_COMMIT_BRANCH"
  script:
    - uvx python-semantic-release version

build_and_push_images:
  stage: build
  tags: [unix]
  rules:
    - if: '$CI_COMMIT_TAG'
  before_script:
    - |
      set -euo pipefail
      echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
      export IMAGE_TAG="${CI_COMMIT_TAG#v}"
      echo "Image Tag: $IMAGE_TAG"
  script:
    # backend
    - docker build -f maskql/Dockerfile -t docker.io/rudymerieux/maskql:$IMAGE_TAG ./maskql
    - docker tag docker.io/rudymerieux/maskql:$IMAGE_TAG docker.io/rudymerieux/maskql:latest
    - docker push docker.io/rudymerieux/maskql:$IMAGE_TAG
    - docker push docker.io/rudymerieux/maskql:latest

    # frontend
    - docker build -f frontend/Dockerfile -t docker.io/rudymerieux/maskql-frontend:$IMAGE_TAG ./frontend
    - docker tag docker.io/rudymerieux/maskql-frontend:$IMAGE_TAG docker.io/rudymerieux/maskql-frontend:latest
    - docker push docker.io/rudymerieux/maskql-frontend:$IMAGE_TAG
    - docker push docker.io/rudymerieux/maskql-frontend:latest

    # maskql-trino
    - docker build -f trino/Dockerfile -t docker.io/rudymerieux/maskql-trino:$IMAGE_TAG ./trino
    - docker tag docker.io/rudymerieux/maskql-trino:$IMAGE_TAG docker.io/rudymerieux/maskql-trino:latest
    - docker push docker.io/rudymerieux/maskql-trino:$IMAGE_TAG
    - docker push docker.io/rudymerieux/maskql-trino:latest