networks:
  private: {}
  public: {}


volumes:
  trino_data:

services:
  postgres:
    image: postgres:16
    networks: [private]
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: demo
    volumes:
      - ./tests/postgresql-init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  trino:
    build: ./trino
    networks: [private]
    volumes:
      - trino_data:/data/trino
    environment:
      TRINO_SHARED_SECRET: "/wasSj8niUsV5si9fnXiRC7nfM2p2acptOh2Jfqoz6o="
    depends_on: [postgres]
    healthcheck:
      # Trino is ready when /v1/info return "starting": false
      test: ["CMD-SHELL", "curl -sf http://localhost:8080/v1/info | grep -q '\"starting\":false'"]
      interval: 5s
      timeout: 3s
      retries: 60
      start_period: 15s

  maskql:
    build: ./maskql
    depends_on:
      trino:
        condition: service_healthy
    networks: [private, public]
    environment:
      - TRINO_URL=http://trino:8080
      - DEMO_USER=admin
      - DEMO_PASS=admin
    volumes:
      - ./maskql/tls:/etc/maskql/tls:ro
    ports:
      - "8443:8443"   # HTTPS
    restart: unless-stopped
