[tox]
env_list = int
requires = tox>=4

[testenv:int]
description = Up (make), healthcheck Trino, unittest, down
package = skip
skip_install = true
basepython = python3

passenv =
    DOCKER_HOST
    TRINO_URL
setenv =
    TRINO_HOST=localhost
    TRINO_PORT=8080
    TRINO_USER=admin
    ; TRINO_PASSWORD= 
    TRINO_CATALOG=postgres
    TRINO_SCHEMA=public
allowlist_externals =
    curl
    make
    uv
    sleep
    timeout
commands_pre =
    make local
    # Wait for trino to start
    timeout 120 bash -c 'until [ "$(curl -sf -u admin:admin http://localhost:8080/v1/info | grep -o "\"starting\":[^,}]*" | cut -d: -f2 | tr -d " \t")" = "false" ]; do sleep 2; done'
    sleep 5
commands =
    uv run python -m unittest discover tests
commands_post =
    make down
