coordinator=true
node-scheduler.include-coordinator=true
http-server.http.port=8080
discovery.uri=http://localhost:8080
plugin.dir=/usr/lib/trino/plugin
internal-communication.shared-secret=${ENV:TRINO_SHARED_SECRET}
web-ui.enabled=false
catalog.management=dynamic
catalog.store=file
